Resources:
  WebServerInstance:
    Type: 'AWS::EC2::Instance'
    Metadata:
      Comment: Install a simple PHP application
      'AWS::CloudFormation::Init':
        config:
          packages:
            yum:
              httpd: []
              php: []
              mysql-server: []
              mysql-libs: []
              mysql: []
          files:
            /var/www/html/index.php:
              content:
                'Fn::Join':
                  - ''
                  - - |
                      <?php
                    - |
                      echo '<h1>AWS CloudFormation sample PHP application</h1>';
                    - echo '<p>Updated version via UpdateStack</p>';
                    - |
                      ?>
              mode: '000644'
              owner: apache
              group: apache
            /etc/cfn/cfn-hup.conf:
              content:
                'Fn::Join':
                  - ''
                  - - |
                      [main]
                    - stack=
                    - Ref: 'AWS::StackId'
                    - |+

                    - region=
                    - Ref: 'AWS::Region'
                    - |+

              mode: '000400'
              owner: root
              group: root
            /etc/cfn/hooks.d/cfn-auto-reloader.conf:
              content:
                'Fn::Join':
                  - ''
                  - - |
                      [cfn-auto-reloader-hook]
                    - |
                      triggers=post.update
                    - >
                      path=Resources.WebServerInstance.Metadata.AWS::CloudFormation::Init
                    - 'action=/opt/aws/bin/cfn-init -s '
                    - Ref: 'AWS::StackId'
                    - ' -r WebServerInstance '
                    - ' --region     '
                    - Ref: 'AWS::Region'
                    - |+

                    - |
                      runas=root
          services:
            sysvinit:
              httpd:
                enabled: 'true'
                ensureRunning: 'true'
              cfn-hup:
                enabled: 'true'
                ensureRunning: 'true'
                files:
                  - /etc/cfn/cfn-hup.conf
                  - /etc/cfn/hooks.d/cfn-auto-reloader.conf
              mysqld:
                enabled: 'true'
                ensureRunning: 'true'
